apiVersion: apps/v1
kind: Deployment
metadata:
  name: slave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: slave
  template:
    metadata:
      labels:
        app: slave
    spec:
      containers:
        - name: slave
          image: zynx01/slave:v1
          resources:
          securityContext:
            privileged: true
          ports:
            - containerPort: 22
